#define CT_OFF_UNITVARS_MINSIZE__ 6

#define CT_OFF_UNITVARS_CLASSNAME 0
#define CT_OFF_UNITVARS_DESCRIPTION 1
#define CT_OFF_UNITVARS_DEFAULTVALUE 2
#define CT_OFF_UNITVARS_LOCAL 3
#define CT_OFF_UNITVARS_ISLIVE 4

#define CT_OFF_UNITVARS_EVENTS 5
#define CT_OFF_UNITVARS_EVENTS_SIZE__ 4
#define CT_OFF_UNITVARS_EVENTS_INIT 0
#define CT_OFF_UNITVARS_EVENTS_UNINIT 1
#define CT_OFF_UNITVARS_EVENTS_LOCALITYCHANGE 2
#define CT_OFF_UNITVARS_EVENTS_LOCALITYCHANGED 3