#define BODY_VAR_BLEEDINGHITS "BODY_BleedingHits"
#define BODY_OFF_BLEEDINGHITS_PROJECTILE 0
#define BODY_OFF_BLEEDINGHITS_SIZE 1
#define BODY_OFF_BLEEDINGHITS_HEAL_STATE 2

#define BODY_BLEEDINGHITS_AUTO_HEAL_MAX_SIZE 1.5
#define BODY_BLEEDINGHITS_HEAL_PER_TICK 0.025


#define BODY_VAR_BLEEDINGHITS "BODY_BloodValue"
#define BODY_BLEEDINGHITS_REPLENISH_PER_TICK 0.001
