#include "Base.hpp"
#include "Wounding/Wound_Head.hpp"
#include "Wounding/Wound_Body.hpp"
#include "Wounding/Wound_LeftFoot.hpp"
#include "Wounding/Wound_LeftHand.hpp"
#include "Wounding/Wound_LeftLowerArm.hpp"
#include "Wounding/Wound_LeftLowerLeg.hpp"
#include "Wounding/Wound_LeftUpperArm.hpp"
#include "Wounding/Wound_LeftUpperLeg.hpp"
#include "Wounding/Wound_RightFoot.hpp"
#include "Wounding/Wound_RightHand.hpp"
#include "Wounding/Wound_RightLowerArm.hpp"
#include "Wounding/Wound_RightLowerLeg.hpp"
#include "Wounding/Wound_RightUpperArm.hpp"
#include "Wounding/Wound_RightUpperLeg.hpp"
#include "Wounding/Wound_Rips.hpp"

