#define EX_OFF_ID 0
#define EX_OFF_MSG 1
#define EX_OFF_STACKTRACE 2
#define EX_OFF_CONTENT 3

#define EX_ID_GENERIC_ERROR 0
#define EX_ID_GENERIC_INVALID_ARG 1
#define EX_ID_GENERIC_INVALID_LOCALITY 2
#define EX_ID_GENERIC_NOTIMPLEMENTED 3


#define EX_ID_DRUG_LINK_SELF 4
#define EX_ID_DRUG_LINK_UNKNOWN 5