name = "Extensive Medical System"
prefix = "xms"
mainprefix = "z"
author = "X39"

[files]
include = [
    "mod.cpp",
    "LICENSE.MD",
    "logo_64px.paa",
    "logo_1024px.paa",
]

[properties]
url = "https://github.com/X39/Project-Alcatraz"

[version]
major = 0
minor = 1
patch = 0
build = 0

[asc]
enabled = false
exclude = [
    "scripting/UserInterface/Debug/fn_postInit.sqf",
]

[hemtt.launch]
workshop = [
    "1585582292", # Arma Debug Engine
    "1645973522", # Intercept Minimal Dev
    "450814997",  # CBA_A3
]
parameters = [
    "-preprocDefine=CMD__XMS_DEBUG"
]