name = "Extensive Medical System"
prefix = "xms"
mainprefix = "z"
author = "X39"

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "LICENSE.MD",
    "logo.paa",
]

[properties]
url = "https://github.com/X39/Project-Alcatraz"

[version]
major = 0
minor = 1
patch = 0
build = 0

[asc]
enabled = true