name = "Extensive Medical System"
prefix = "xms"
mainprefix = "z"
author = "X39"

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "LICENSE.MD",
    "logo.paa",
]

[properties]
url = "https://github.com/X39/Project-Alcatraz"

[version]
major = 0
minor = 1
patch = 0
build = 0

[asc]
enabled = false

[hemtt.launch]
workshop = [
    "1585582292", # Arma Debug Engine
    "1645973522", # Intercept Minimal Dev
    "450814997",  # CBA_A3
]
parameters = [
    "C:\\Users\\marco.silipo\\Documents\\Arma 3 - Other Profiles\\X39\\missions\\MOD_Test.Stratis\\mission.sqm"
]