#define CT_OFF_DRUG_MINSIZE__ 9

#define CT_OFF_DRUG_CLASSNAME 0
#define CT_OFF_DRUG_DISPLAYNAME 1
#define CT_OFF_DRUG_TRANSITIONPERTICK 2
#define CT_OFF_DRUG_MAXVALUE 3
#define CT_OFF_DRUG_BLOODTHIKNESS 4
#define CT_OFF_DRUG_PAIN 5
#define CT_OFF_DRUG_VISION 6
#define CT_OFF_DRUG_COLOR 7


#define CT_OFF_DRUG_AFFECTS 8
#define CT_OFF_DRUG_AFFECTS_SIZE__ 2
#define CT_OFF_DRUG_AFFECTS_NAME 0
#define CT_OFF_DRUG_AFFECTS_VALUE 1
#define CT_OFF_DRUG_AFFECTS_CALCULATIONTYPE 2

#define CT_OFF_DRUG_BLACKOUT 9
#define CT_OFF_DRUG_BLACKOUT_SIZE__ 3
#define CT_OFF_DRUG_BLACKOUT_STAGE 0
#define CT_OFF_DRUG_BLACKOUT_CONDITION 1
#define CT_OFF_DRUG_BLACKOUT_FOLLOWEDBY 2

#define CT_OFF_DRUG_ITEMS 10
#define CT_OFF_DRUG_ITEMS_SIZE__ 4
#define CT_OFF_DRUG_ITEMS_DISPLAYNAME 0
#define CT_OFF_DRUG_ITEMS_IMAGE 1
#define CT_OFF_DRUG_ITEMS_CLASSNAME 2
#define CT_OFF_DRUG_ITEMS_VALUE 3


