#define CT_OFF_DRUG_MINSIZE__ 9

#define CT_OFF_DRUG_DISPLAYNAME 0
#define CT_OFF_DRUG_TRANSITIONPERTICK 1
#define CT_OFF_DRUG_MAXVALUE 2
#define CT_OFF_DRUG_BLOODTHIKNESS 3
#define CT_OFF_DRUG_PAIN 4
#define CT_OFF_DRUG_VISION 5


#define CT_OFF_DRUG_AFFECTS 6
#define CT_OFF_DRUG_AFFECTS_SIZE__ 2
#define CT_OFF_DRUG_AFFECTS_NAME 0
#define CT_OFF_DRUG_AFFECTS_VALUE 1

#define CT_OFF_DRUG_BLACKOUT 7
#define CT_OFF_DRUG_BLACKOUT_SIZE__ 3
#define CT_OFF_DRUG_BLACKOUT_STAGE 0
#define CT_OFF_DRUG_BLACKOUT_CONDITION 1
#define CT_OFF_DRUG_BLACKOUT_FOLLOWEDBY 2

#define CT_OFF_DRUG_ITEMS 8
#define CT_OFF_DRUG_ITEMS_SIZE__ 4
#define CT_OFF_DRUG_ITEMS_DISPLAYNAME 0
#define CT_OFF_DRUG_ITEMS_IMAGE 1
#define CT_OFF_DRUG_ITEMS_CLASSNAME 2
#define CT_OFF_DRUG_ITEMS_VALUE 3


